use arboard::{Clipboard, ImageData};
use clipboard_master::{CallbackResult, ClipboardHandler, Master};
use image::{DynamicImage, ImageBuffer, RgbaImage};
use std::sync::{mpsc, Arc, Mutex};
use tauri::{AppHandle, Emitter, Manager};
use uuid::Uuid;

use crate::storage::{encode_file_paths, ClipItem, ContentType, CopyMarker};
use crate::{paste::CopyWrite, settings::Settings, AppState};

#[cfg(target_os = "windows")]
#[link(name = "kernel32")]
extern "system" {
    fn GlobalLock(hmem: windows::Win32::Foundation::HANDLE) -> *mut std::ffi::c_void;
    fn GlobalSize(hmem: windows::Win32::Foundation::HANDLE) -> usize;
    fn GlobalUnlock(hmem: windows::Win32::Foundation::HANDLE) -> i32;
}

struct Handler {
    app_handle: AppHandle,
    last_copied_by_us: Arc<Mutex<Option<CopyWrite>>>,
    last_marker: Option<CopyMarker>,
}

struct ProcessedClipboardImage {
    content_png: Vec<u8>,
    thumbnail_png: Vec<u8>,
}

/// A single representative view of the current clipboard, chosen by priority so
/// one clipboard change yields exactly one record: `Files > Text(+html) > Image`.
/// Finder's file copies also expose a filename string and an icon image;
/// taking the file list first discards that derived noise.
enum ClipboardSnapshot {
    Files(Vec<String>),
    Text { text: String, html: Option<String> },
    Image(ImageData<'static>),
}

/// Reads the clipboard once and returns its single representative format.
///
/// Image decoding copies the full bitmap and is expensive, so it is only
/// attempted when neither files nor text are present.
fn read_clipboard_snapshot(clipboard: &mut Clipboard) -> Option<ClipboardSnapshot> {
    if let Ok(paths) = clipboard.get().file_list() {
        let paths: Vec<String> = paths
            .into_iter()
            .map(|path| path.to_string_lossy().into_owned())
            .filter(|path| !path.is_empty())
            .collect();
        if !paths.is_empty() {
            return Some(ClipboardSnapshot::Files(paths));
        }
    }

    if let Ok(text) = clipboard.get_text() {
        if !text.is_empty() {
            // HTML is an optional companion; a missing or empty value is normal.
            let html = clipboard.get().html().ok().filter(|html| !html.is_empty());
            return Some(ClipboardSnapshot::Text { text, html });
        }
    }

    if let Ok(image) = clipboard.get_image() {
        return Some(ClipboardSnapshot::Image(image));
    }

    None
}

/// Self-copy/dedup marker for a snapshot, hashing only the primary content.
/// Text hashes the plain text (never the html), because after a self-paste the
/// monitor reads back the plain-text alt and must still recognize our write.
fn snapshot_marker(snapshot: &ClipboardSnapshot) -> CopyMarker {
    match snapshot {
        ClipboardSnapshot::Files(paths) => {
            CopyMarker::from_payload(ContentType::Files, encode_file_paths(paths).as_bytes())
        }
        ClipboardSnapshot::Text { text, .. } => {
            CopyMarker::from_payload(ContentType::Text, text.as_bytes())
        }
        ClipboardSnapshot::Image(image) => {
            CopyMarker::from_normalized_image_parts(image.width, image.height, image.bytes.as_ref())
        }
    }
}

/// 同文富文本需要重新经过过滤和保存；自身写入仍推进标记并跳过捕获。
fn record_marker_and_decide_dispatch(
    marker: &CopyMarker,
    last_marker: &mut Option<CopyMarker>,
    capture_rich_text: bool,
    is_self_copied: impl FnOnce() -> bool,
) -> bool {
    if last_marker.as_ref() == Some(marker) && !capture_rich_text {
        return false;
    }
    *last_marker = Some(marker.clone());
    !is_self_copied()
}

impl ClipboardHandler for Handler {
    fn on_clipboard_change(&mut self) -> CallbackResult {
        let mut clipboard = match Clipboard::new() {
            Ok(cb) => cb,
            Err(e) => {
                log::error!("Failed to create clipboard instance in handler: {}", e);
                return CallbackResult::Next;
            }
        };

        if should_ignore_current_clipboard(&self.app_handle) {
            log::info!("Skipping clipboard change marked as concealed/transient/autogenerated");
            return CallbackResult::Next;
        }

        handle_clipboard_event(
            &self.app_handle,
            &self.last_copied_by_us,
            &mut clipboard,
            &mut self.last_marker,
        );

        CallbackResult::Next
    }

    fn on_clipboard_error(&mut self, error: std::io::Error) -> CallbackResult {
        log::error!("Clipboard error: {}", error);
        CallbackResult::Next
    }
}

/// 启动剪贴板监听线程。`Master::new` 的错误返回给调用方；`run()` 只在系统剪贴板
/// 不可用时返回错误，此时应用无法继续工作，直接 panic。
pub fn start_monitor(
    app_handle: AppHandle,
    last_copied_by_us: Arc<Mutex<Option<CopyWrite>>>,
) -> Result<(), String> {
    let (ready_sender, ready_receiver) = mpsc::channel();

    std::thread::spawn(move || {
        let handler = Handler {
            app_handle,
            last_copied_by_us,
            last_marker: None,
        };
        let mut master = match Master::new(handler) {
            Ok(master) => master,
            Err(e) => {
                ready_sender
                    .send(Err(format!("Failed to create clipboard master: {e}")))
                    .expect("start_monitor waits for the ready message");
                return;
            }
        };
        ready_sender
            .send(Ok(()))
            .expect("start_monitor waits for the ready message");
        if let Err(e) = master.run() {
            panic!("Clipboard monitoring stopped: {e}");
        }
    });

    ready_receiver
        .recv()
        .map_err(|e| format!("Clipboard monitor failed to start: {e}"))?
}

/// Read one representative snapshot, dedup against `last_marker`, skip our own
/// writes, then dispatch a single record for the winning format.
fn handle_clipboard_event(
    app_handle: &AppHandle,
    last_copied_by_us: &Arc<Mutex<Option<CopyWrite>>>,
    clipboard: &mut Clipboard,
    last_marker: &mut Option<CopyMarker>,
) {
    let settings = app_handle.state::<AppState>().settings.get();
    // 暂停期间完全不观察剪贴板，`last_marker` 也不推进：恢复后第一次读取的内容与暂停前
    // 最后记录的内容比较，行为与未暂停时一致。
    if settings.capture_paused {
        return;
    }

    let sequence = crate::paste::clipboard_sequence();
    let Some(snapshot) = read_clipboard_snapshot(clipboard) else {
        return;
    };
    if sequence != crate::paste::clipboard_sequence() {
        return;
    }
    let marker = snapshot_marker(&snapshot);

    let capture_rich_text = matches!(&snapshot, ClipboardSnapshot::Text { html: Some(_), .. })
        && settings.strips_rich_text_at_capture();
    if !record_marker_and_decide_dispatch(&marker, last_marker, capture_rich_text, || {
        is_self_copied(last_copied_by_us, &marker)
    }) {
        return;
    }

    // 前台应用在分派前同步读取：图片在后台任务中处理，来源必须在那之前确定。
    let (source_app, source_id) = frontmost_app();

    // 应用排除放在推进 `last_marker` 之后，与自身复制的跳过相同：否则之后的复制会与
    // 过期的记录比较。
    if [source_id.as_deref(), source_app.as_deref()]
        .into_iter()
        .flatten()
        .any(|identity| app_name_matches_ignore_list(identity, &settings.ignored_apps))
    {
        log::debug!("Skipping clipboard change from an excluded application");
        return;
    }

    match snapshot {
        ClipboardSnapshot::Files(paths) => {
            process_files_change(app_handle, paths, source_app, &settings)
        }
        ClipboardSnapshot::Text { text, html } => {
            process_text_change(app_handle, &text, html, source_app, sequence, &settings)
        }
        ClipboardSnapshot::Image(image) => {
            process_image_change(app_handle, image, source_app, settings.max_image_dimension)
        }
    }
}

fn process_text_change(
    app_handle: &AppHandle,
    text: &str,
    html: Option<String>,
    source_app: Option<String>,
    sequence: Option<u64>,
    settings: &Settings,
) {
    if let Some(html) = capture_text(text, html, source_app, settings, |item| {
        save_to_storage(app_handle, item)
    }) {
        strip_live_rich_text(app_handle, text, &html, sequence);
    }
}

/// 持锁核对捕获后剪贴板没有被再次写入，避免覆盖保存期间发生的另一次复制或粘贴。
fn strip_live_rich_text(app_handle: &AppHandle, text: &str, html: &str, sequence: Option<u64>) {
    let state = app_handle.state::<AppState>();
    let Ok(_operation) = state.clipboard_use_lock.try_lock() else {
        log::debug!("Skipping globalPlain strip: a clipboard use is in flight");
        return;
    };
    let settings = state.settings.get();
    if settings.capture_paused || !settings.strips_rich_text_at_capture() {
        return;
    }
    let marker = CopyMarker::from_payload(ContentType::Text, text.as_bytes());
    if is_self_copied(&state.last_copied_by_us, &marker) {
        return;
    }
    let unchanged = match sequence {
        // 系统剪贴板序号未变，说明捕获后没有新的写入。
        Some(sequence) => crate::paste::clipboard_sequence() == Some(sequence),
        // Linux 的 arboard 不提供序号，只能核对完整内容。
        None => {
            let Ok(mut clipboard) = Clipboard::new() else {
                return;
            };
            !clipboard
                .get()
                .file_list()
                .is_ok_and(|paths| !paths.is_empty())
                && clipboard.get_text().ok().as_deref() == Some(text)
                && clipboard.get().html().ok().as_deref() == Some(html)
        }
    };
    if !unchanged {
        return;
    }
    if let Err(e) = crate::paste::strip_rich_text_from_clipboard(text, &state.last_copied_by_us) {
        log::warn!("Failed to strip rich text from clipboard: {}", e);
    }
}

fn process_files_change(
    app_handle: &AppHandle,
    paths: Vec<String>,
    source_app: Option<String>,
    settings: &Settings,
) {
    let content = encode_file_paths(&paths).into_bytes();

    if content.len() > settings.max_text_bytes {
        log::info!(
            "Skipping files clip: {} bytes exceeds max_text_bytes ({})",
            content.len(),
            settings.max_text_bytes
        );
        return;
    }

    log::info!("Files clipboard changed: {} path(s)", paths.len());
    let item = ClipItem {
        id: Uuid::new_v4().to_string(),
        content,
        thumbnail: None,
        content_type: ContentType::Files,
        timestamp: crate::storage::current_timestamp(),
        is_pinned: false,
        pin_order: None,
        label: None,
        source_app,
        html: None,
    };
    save_to_storage(app_handle, item);
}

fn process_image_change(
    app_handle: &AppHandle,
    image: ImageData<'static>,
    source_app: Option<String>,
    max_image_dimension: u32,
) {
    let captured_at = crate::storage::current_timestamp();
    let width = image.width;
    let height = image.height;
    // arboard 返回的是 `Cow::Owned`，`into_owned` 直接取得缓冲区，不复制。
    let rgba_bytes = image.bytes.into_owned();
    log::info!(
        "Image clipboard changed: {}x{}, {} RGBA bytes",
        width,
        height,
        rgba_bytes.len()
    );

    let app_handle = app_handle.clone();
    tauri::async_runtime::spawn_blocking(move || {
        match process_clipboard_image(width, height, rgba_bytes, max_image_dimension) {
            Ok(processed) => {
                let item = ClipItem {
                    id: Uuid::new_v4().to_string(),
                    content: processed.content_png,
                    thumbnail: Some(processed.thumbnail_png),
                    content_type: ContentType::Image,
                    timestamp: captured_at,
                    is_pinned: false,
                    pin_order: None,
                    label: None,
                    source_app,
                    html: None,
                };
                save_to_storage(&app_handle, item);
            }
            Err(e) => log::error!("Failed to process clipboard image: {}", e),
        }
    });
}

fn should_ignore_current_clipboard(app_handle: &AppHandle) -> bool {
    app_handle
        .state::<AppState>()
        .settings
        .get()
        .ignore_concealed
        && clipboard_has_sensitive_marker()
}

fn is_self_copied(
    last_copied_by_us: &Arc<Mutex<Option<CopyWrite>>>,
    expected_marker: &CopyMarker,
) -> bool {
    last_copied_by_us
        .lock()
        .unwrap()
        .as_ref()
        .is_some_and(|write| write.matches(expected_marker))
}

/// Persist a captured item. Returns false only when the insert failed —
/// `Ok(None)` (item fell outside the history limit) still counts as
/// persisted, since the live-clipboard strip decision must not depend on
/// history-limit pruning.
fn save_to_storage(app_handle: &AppHandle, item: ClipItem) -> bool {
    use crate::storage::FrontendClipItem;
    use crate::tray::update_tray_menu;

    let state = app_handle.state::<AppState>();
    let max_history_items = state.settings.get().max_history_items;

    let result = {
        let storage = state.storage.lock().unwrap();

        storage
            .insert(&item, max_history_items)
            .and_then(|existing_id| {
                // A delayed old image may already have been pruned; never emit a ghost row.
                storage
                    .get_preview_by_id(existing_id.as_deref().unwrap_or(&item.id))
                    .map(|item| item.map(FrontendClipItem::from_preview))
            })
    };

    match result {
        Ok(Some(item_for_emit)) => {
            app_handle.emit("clipboard-changed", &item_for_emit).ok();
            update_tray_menu(app_handle);
            true
        }
        Ok(None) => {
            log::debug!("Captured item was already outside the history limit");
            true
        }
        Err(e) => {
            log::error!("Failed to save clipboard item: {}", e);
            false
        }
    }
}

fn process_clipboard_image(
    width: usize,
    height: usize,
    rgba_bytes: Vec<u8>,
    max_image_dimension: u32,
) -> Result<ProcessedClipboardImage, String> {
    const THUMBNAIL_SIZE: u32 = 256;

    let image: RgbaImage = ImageBuffer::from_raw(width as u32, height as u32, rgba_bytes)
        .ok_or_else(|| "Invalid clipboard image buffer dimensions".to_string())?;
    let image = DynamicImage::ImageRgba8(image);
    let image = downscale_if_oversized(image, max_image_dimension);

    let content_png = encode_png(&image)?;
    let thumbnail_png = if image.width() <= THUMBNAIL_SIZE && image.height() <= THUMBNAIL_SIZE {
        content_png.clone()
    } else {
        encode_png(&image.resize(
            THUMBNAIL_SIZE,
            THUMBNAIL_SIZE,
            image::imageops::FilterType::Lanczos3,
        ))?
    };

    log::info!(
        "Processed clipboard image: {}x{} -> {} bytes, thumbnail {} bytes",
        image.width(),
        image.height(),
        content_png.len(),
        thumbnail_png.len()
    );

    Ok(ProcessedClipboardImage {
        content_png,
        thumbnail_png,
    })
}

fn encode_png(image: &DynamicImage) -> Result<Vec<u8>, String> {
    let mut buffer = Vec::new();
    image
        .write_to(
            &mut std::io::Cursor::new(&mut buffer),
            image::ImageFormat::Png,
        )
        .map_err(|e| format!("Failed to encode PNG: {}", e))?;
    Ok(buffer)
}

/// Downsamples an oversized clipboard image so its longest side fits within
/// `max_dimension`, preserving aspect ratio. `0` disables downscaling (the
/// settings page allows it). Images already within the limit are returned
/// untouched.
fn downscale_if_oversized(image: DynamicImage, max_dimension: u32) -> DynamicImage {
    if max_dimension == 0 {
        return image;
    }

    let longest_side = image.width().max(image.height());
    if longest_side <= max_dimension {
        return image;
    }

    log::info!(
        "Downsampling oversized clipboard image {}x{} to fit within {}px",
        image.width(),
        image.height(),
        max_dimension
    );
    image.resize(
        max_dimension,
        max_dimension,
        image::imageops::FilterType::Lanczos3,
    )
}

/// 通过过滤且保存成功后，返回清理时需要核对的原始 HTML。
fn capture_text(
    text: &str,
    html: Option<String>,
    source_app: Option<String>,
    settings: &Settings,
    save: impl FnOnce(ClipItem) -> bool,
) -> Option<String> {
    if text.len() > settings.max_text_bytes {
        log::info!(
            "Skipping text clip: {} bytes exceeds max_text_bytes ({})",
            text.len(),
            settings.max_text_bytes
        );
        return None;
    }
    if settings.skip_secrets {
        if let Some(kind) = crate::secrets::detect_secret(text) {
            log::info!("Skipping captured secret ({kind})");
            return None;
        }
    }

    // 存储大小限制不会改变系统剪贴板，清理时仍需核对完整 HTML。
    let strip_html = settings
        .strips_rich_text_at_capture()
        .then(|| html.clone())
        .flatten();
    let item = ClipItem {
        id: Uuid::new_v4().to_string(),
        content: text.as_bytes().to_vec(),
        thumbnail: None,
        content_type: ContentType::Text,
        timestamp: crate::storage::current_timestamp(),
        is_pinned: false,
        pin_order: None,
        label: None,
        source_app,
        html: clamp_html_to_size_limit(html, settings.max_text_bytes),
    };
    log::info!("Text clipboard changed: {} chars", text.len());
    if save(item) {
        strip_html
    } else {
        None
    }
}

/// 大小写不敏感地匹配排除名单；名单的首尾空白已在 settings.rs 去除。
fn app_name_matches_ignore_list(app_name: &str, ignored_apps: &[String]) -> bool {
    let app_name = app_name.to_lowercase();
    ignored_apps
        .iter()
        .any(|ignored| ignored.to_lowercase() == app_name)
}

/// Drops an html companion that exceeds `max_text_bytes`, keeping only the
/// plain text. HTML is optional metadata, so an oversized html on an
/// otherwise-fine text clip degrades to plain text rather than skipping the
/// whole clip.
fn clamp_html_to_size_limit(html: Option<String>, max_text_bytes: usize) -> Option<String> {
    html.filter(|html| {
        let within_limit = html.len() <= max_text_bytes;
        if !within_limit {
            log::debug!(
                "Dropping oversized html companion: {} bytes exceeds max_text_bytes ({})",
                html.len(),
                max_text_bytes
            );
        }
        within_limit
    })
}

#[cfg(target_os = "macos")]
fn clipboard_has_sensitive_marker() -> bool {
    use objc2_app_kit::NSPasteboard;

    const IGNORED_PASTEBOARD_TYPES: &[&str] = &[
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ];

    let pasteboard = NSPasteboard::generalPasteboard();
    let Some(types) = pasteboard.types() else {
        return false;
    };

    for pasteboard_type in types.iter() {
        let type_name = pasteboard_type.to_string();

        if IGNORED_PASTEBOARD_TYPES.contains(&type_name.as_str()) {
            log::info!("Skipping macOS pasteboard marker type: {}", type_name);
            return true;
        }
    }

    false
}

#[cfg(target_os = "windows")]
fn clipboard_has_sensitive_marker() -> bool {
    use windows::Win32::Foundation::HWND;
    use windows::Win32::System::DataExchange::{CloseClipboard, OpenClipboard};

    unsafe {
        if let Err(e) = OpenClipboard(HWND(std::ptr::null_mut())) {
            log::warn!("Failed to open clipboard for privacy marker check: {}", e);
            return false;
        }

        let should_ignore = windows_clipboard_has_exclude_marker()
            || windows_can_include_clipboard_history_is_false();

        if let Err(e) = CloseClipboard() {
            log::warn!(
                "Failed to close clipboard after privacy marker check: {}",
                e
            );
        }

        should_ignore
    }
}

#[cfg(target_os = "windows")]
fn windows_clipboard_has_exclude_marker() -> bool {
    let format = windows_clipboard_format("ExcludeClipboardContentFromMonitorProcessing");
    if windows_clipboard_format_available(format) {
        log::info!("Skipping Windows clipboard history monitor opt-out marker");
        return true;
    }

    false
}

#[cfg(target_os = "windows")]
fn windows_can_include_clipboard_history_is_false() -> bool {
    let format = windows_clipboard_format("CanIncludeInClipboardHistory");
    if !windows_clipboard_format_available(format) {
        return false;
    }

    if windows_clipboard_dword(format) == Some(0) {
        log::info!("Skipping Windows clipboard history include marker set to 0");
        return true;
    }

    false
}

#[cfg(target_os = "windows")]
fn windows_clipboard_format(name: &str) -> u32 {
    use windows::core::PCWSTR;
    use windows::Win32::System::DataExchange::RegisterClipboardFormatW;

    let wide_name: Vec<u16> = name.encode_utf16().chain(std::iter::once(0)).collect();
    unsafe { RegisterClipboardFormatW(PCWSTR(wide_name.as_ptr())) }
}

#[cfg(target_os = "windows")]
fn windows_clipboard_format_available(format: u32) -> bool {
    use windows::Win32::System::DataExchange::IsClipboardFormatAvailable;

    format != 0 && unsafe { IsClipboardFormatAvailable(format).is_ok() }
}

#[cfg(target_os = "windows")]
fn windows_clipboard_dword(format: u32) -> Option<u32> {
    use windows::Win32::System::DataExchange::GetClipboardData;

    unsafe {
        let handle = GetClipboardData(format).ok()?;
        if handle.is_invalid() || GlobalSize(handle) < std::mem::size_of::<u32>() {
            return None;
        }

        let data = GlobalLock(handle);
        if data.is_null() {
            return None;
        }

        let bytes = std::slice::from_raw_parts(data.cast::<u8>(), std::mem::size_of::<u32>());
        let value = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
        let _ = GlobalUnlock(handle);
        Some(value)
    }
}

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
fn clipboard_has_sensitive_marker() -> bool {
    false
}

/// Localized name of the app that was frontmost at capture time — the source
/// the clip was copied from. Returns None when ClipMan itself is frontmost or
/// the name is unavailable.
// ponytail: reads NSWorkspace off the monitor thread, same as window.rs does
// off the command thread; AppKit's frontmostApplication tolerates it.
#[cfg(target_os = "macos")]
fn frontmost_app() -> (Option<String>, Option<String>) {
    use objc2_app_kit::NSWorkspace;

    let Some(front) = NSWorkspace::sharedWorkspace().frontmostApplication() else {
        return (None, None);
    };
    if front.processIdentifier() == std::process::id() as i32 {
        return (None, None);
    }
    (
        front.localizedName().map(|name| name.to_string()),
        front.bundleIdentifier().map(|id| id.to_string()),
    )
}

#[cfg(not(target_os = "macos"))]
fn frontmost_app() -> (Option<String>, Option<String>) {
    (None, None)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn oversized_image_is_downsampled_to_max_dimension() {
        let width = 2000;
        let height = 1000;
        let rgba_bytes = vec![200u8; width * height * 4];

        let processed = process_clipboard_image(width, height, rgba_bytes, 500).unwrap();
        let content = image::load_from_memory(&processed.content_png).unwrap();

        assert_eq!(500, content.width());
        assert_eq!(250, content.height());

        // The (unrelated) thumbnail pipeline still runs on the downsampled
        // image and stays within its own 256px bound.
        let thumbnail = image::load_from_memory(&processed.thumbnail_png).unwrap();
        assert!(thumbnail.width() <= 256 && thumbnail.height() <= 256);
    }

    #[test]
    fn small_image_is_not_resized_and_reuses_png_as_thumbnail() {
        let width = 100;
        let height = 50;
        let rgba_bytes = vec![5u8; width * height * 4];

        let processed = process_clipboard_image(width, height, rgba_bytes, 4096).unwrap();
        let content = image::load_from_memory(&processed.content_png).unwrap();

        assert_eq!(width as u32, content.width());
        assert_eq!(height as u32, content.height());
        assert_eq!(processed.content_png, processed.thumbnail_png);
    }

    #[test]
    fn max_image_dimension_zero_disables_downscaling() {
        let width = 3000;
        let height = 1;
        let rgba_bytes = vec![10u8; width * height * 4];

        let processed = process_clipboard_image(width, height, rgba_bytes, 0).unwrap();
        let content = image::load_from_memory(&processed.content_png).unwrap();

        assert_eq!(width as u32, content.width());
        assert_eq!(height as u32, content.height());
    }

    #[test]
    fn oversized_html_is_dropped_but_undersized_html_and_missing_html_are_kept() {
        let big_html = "x".repeat(101);
        assert_eq!(None, clamp_html_to_size_limit(Some(big_html), 100));

        let small_html = "x".repeat(100);
        assert_eq!(
            Some(small_html.clone()),
            clamp_html_to_size_limit(Some(small_html), 100)
        );

        assert_eq!(None, clamp_html_to_size_limit(None, 100));
    }

    #[test]
    fn app_name_matches_ignore_list_is_case_insensitive() {
        let ignored = vec!["Safari".to_string(), "1Password".to_string()];

        assert!(app_name_matches_ignore_list("safari", &ignored));
        assert!(app_name_matches_ignore_list("SAFARI", &ignored));
        assert!(app_name_matches_ignore_list("1password", &ignored));
        assert!(!app_name_matches_ignore_list("Notes", &ignored));
        assert!(!app_name_matches_ignore_list("Safari", &[]));
    }

    #[test]
    fn snapshot_marker_matches_primary_content_and_ignores_html() {
        // Files hash the lossless encoded path list.
        let paths = vec!["/a/b.txt".to_string(), "/c/d.png".to_string()];
        assert_eq!(
            CopyMarker::from_payload(ContentType::Files, encode_file_paths(&paths).as_bytes()),
            snapshot_marker(&ClipboardSnapshot::Files(paths.clone()))
        );

        // Text hashes only the plain text: identical text with different html
        // produces the same marker.
        let plain = snapshot_marker(&ClipboardSnapshot::Text {
            text: "hello".to_string(),
            html: None,
        });
        let rich = snapshot_marker(&ClipboardSnapshot::Text {
            text: "hello".to_string(),
            html: Some("<b>hello</b>".to_string()),
        });
        assert_eq!(CopyMarker::from_payload(ContentType::Text, b"hello"), plain);
        assert_eq!(plain, rich);

        // Image hashes normalized dimensions + RGBA bytes.
        let bytes = vec![1u8, 2, 3, 4];
        let image = ImageData {
            width: 1,
            height: 1,
            bytes: std::borrow::Cow::Owned(bytes.clone()),
        };
        assert_eq!(
            CopyMarker::from_normalized_image_parts(1, 1, &bytes),
            snapshot_marker(&ClipboardSnapshot::Image(image))
        );
    }

    #[test]
    fn self_copy_skip_still_advances_last_marker() {
        let marker = CopyMarker::from_payload(ContentType::Text, b"hello");
        let mut last_marker = None;

        // The first observation is our own paste: skip dispatch, but still record
        // the marker so the next genuine copy of *different* content is not
        // compared against stale None state.
        assert!(!record_marker_and_decide_dispatch(
            &marker,
            &mut last_marker,
            false,
            || true
        ));
        assert_eq!(Some(&marker), last_marker.as_ref());

        // Observing the same content again deduplicates without even consulting
        // the self-copy check.
        assert!(!record_marker_and_decide_dispatch(
            &marker,
            &mut last_marker,
            false,
            || panic!("unchanged marker must not re-check self-copy")
        ));
        assert_eq!(Some(&marker), last_marker.as_ref());

        // Genuinely new content we did not copy: dispatch and advance.
        let next = CopyMarker::from_payload(ContentType::Text, b"world");
        assert!(record_marker_and_decide_dispatch(
            &next,
            &mut last_marker,
            false,
            || false
        ));
        assert_eq!(Some(&next), last_marker.as_ref());
    }

    #[test]
    fn global_plain_recaptures_rich_text_with_the_same_plain_marker() {
        let marker = CopyMarker::from_payload(ContentType::Text, b"hello");
        let mut last_marker = None;
        assert!(record_marker_and_decide_dispatch(
            &marker,
            &mut last_marker,
            false,
            || false
        ));
        assert!(record_marker_and_decide_dispatch(
            &marker,
            &mut last_marker,
            true,
            || false
        ));
        assert!(!record_marker_and_decide_dispatch(
            &marker,
            &mut last_marker,
            true,
            || true
        ));
    }

    #[test]
    fn rich_text_is_stripped_only_after_a_successful_save() {
        let html = "<b>hello</b>";
        for max_text_bytes in [5, 100] {
            let settings = Settings {
                paste_format: "globalPlain".into(),
                max_text_bytes,
                ..Settings::default()
            };
            for persisted in [false, true] {
                let strip_html =
                    capture_text("hello", Some(html.into()), None, &settings, |item| {
                        assert_eq!(item.content, b"hello");
                        assert_eq!(
                            item.html.as_deref(),
                            (html.len() <= max_text_bytes).then_some(html)
                        );
                        persisted
                    });
                assert_eq!(strip_html.as_deref(), persisted.then_some(html));
            }
        }
    }

    #[test]
    fn rejected_text_never_reaches_storage_or_clipboard_stripping() {
        let settings = Settings {
            paste_format: "globalPlain".into(),
            max_text_bytes: 20,
            skip_secrets: true,
            ..Settings::default()
        };
        let secret = ["AKIA", "IOSFODNN7EXAMPLE"].concat();
        for text in [secret.as_str(), "ordinary text exceeding the size limit"] {
            assert_eq!(
                capture_text(text, Some("<b>private</b>".into()), None, &settings, |_| {
                    panic!("被过滤的内容不能进入存储")
                }),
                None
            );
        }
    }
}
