use arboard::{Clipboard, ImageData};
use chrono::Utc;
use clipboard_master::{CallbackResult, ClipboardHandler, Master, Shutdown};
use image::GenericImageView;
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc, Mutex,
};
use std::thread::JoinHandle;
use tauri::{AppHandle, Emitter, Manager};
use uuid::Uuid;

use crate::storage::{ClipItem, ContentType, CopyMarker};

#[cfg(target_os = "windows")]
#[link(name = "kernel32")]
extern "system" {
    fn GlobalLock(hmem: windows::Win32::Foundation::HANDLE) -> *mut std::ffi::c_void;
    fn GlobalSize(hmem: windows::Win32::Foundation::HANDLE) -> usize;
    fn GlobalUnlock(hmem: windows::Win32::Foundation::HANDLE) -> i32;
}

pub struct ClipboardMonitor {
    app_handle: AppHandle,
    last_copied_by_us: Arc<Mutex<Option<CopyMarker>>>,
    running: Arc<AtomicBool>,
    shutdown: Arc<Mutex<Option<Shutdown>>>,
    handle: Option<JoinHandle<()>>,
}

struct Handler {
    app_handle: AppHandle,
    last_copied_by_us: Arc<Mutex<Option<CopyMarker>>>,
    last_text: String,
    last_image: Option<Vec<u8>>,
}

impl ClipboardHandler for Handler {
    fn on_clipboard_change(&mut self) -> CallbackResult {
        let mut clipboard = match Clipboard::new() {
            Ok(cb) => cb,
            Err(e) => {
                log::error!("Failed to create clipboard instance in handler: {}", e);
                return CallbackResult::Next;
            }
        };

        if ClipboardMonitor::should_ignore_current_clipboard(&self.app_handle) {
            log::info!("Skipping clipboard change marked as concealed/transient/autogenerated");
            return CallbackResult::Next;
        }

        // Check for text changes
        if let Ok(text) = clipboard.get_text() {
            if text != self.last_text && !text.is_empty() {
                ClipboardMonitor::process_text_change(
                    &self.app_handle,
                    &self.last_copied_by_us,
                    &text,
                );
                self.last_text = text;
            }
        }

        // Check for image changes
        if let Ok(image) = clipboard.get_image() {
            let payload = ClipboardMonitor::normalize_image_payload(&image);
            if self.last_image.as_ref() != Some(&payload) {
                ClipboardMonitor::process_image_change(
                    &self.app_handle,
                    &self.last_copied_by_us,
                    &image,
                    &payload,
                );
                self.last_image = Some(payload);
            }
        }

        CallbackResult::Next
    }

    fn on_clipboard_error(&mut self, error: std::io::Error) -> CallbackResult {
        log::error!("Clipboard error: {}", error);
        CallbackResult::Next
    }
}

impl ClipboardMonitor {
    pub fn new(app_handle: AppHandle, last_copied_by_us: Arc<Mutex<Option<CopyMarker>>>) -> Self {
        Self {
            app_handle,
            last_copied_by_us,
            running: Arc::new(AtomicBool::new(false)),
            shutdown: Arc::new(Mutex::new(None)),
            handle: None,
        }
    }

    pub fn start(&mut self) {
        self.running.store(true, Ordering::SeqCst);
        let app_handle = self.app_handle.clone();
        let last_copied_by_us = self.last_copied_by_us.clone();
        let running = self.running.clone();
        let shutdown_slot = self.shutdown.clone();

        // Start event-driven monitoring thread
        let handle = std::thread::spawn(move || {
            log::info!("Clipboard monitoring thread started (event-driven)");

            let handler = Handler {
                app_handle: app_handle.clone(),
                last_copied_by_us: last_copied_by_us.clone(),
                last_text: String::new(),
                last_image: None,
            };

            // Start the clipboard master - this blocks until the application exits
            match Master::new(handler) {
                Ok(mut master) => {
                    // Hand the shutdown channel to the monitor so stop() can end
                    // run() from another thread. stop() is only ever called once
                    // the thread is up (during migration), so there is no
                    // start/stop startup race to guard against here.
                    *crate::safe_lock(&shutdown_slot) = Some(master.shutdown_channel());
                    if let Err(e) = master.run() {
                        log::error!("Clipboard master failed: {}", e);
                        log::warn!("Falling back to polling mode...");
                        Self::start_polling(app_handle, last_copied_by_us, running);
                    }
                }
                Err(e) => {
                    log::error!("Failed to create clipboard master: {}", e);
                    log::warn!("Falling back to polling mode...");
                    Self::start_polling(app_handle, last_copied_by_us, running);
                }
            }
        });

        self.handle = Some(handle);
    }

    /// Stop the monitor and wait for its thread to exit.
    pub fn stop(mut self) {
        self.running.store(false, Ordering::SeqCst);
        if let Some(shutdown) = crate::safe_lock(&self.shutdown).take() {
            shutdown.signal();
        }
        if let Some(handle) = self.handle.take() {
            let _ = handle.join();
        }
    }

    // Fallback polling implementation
    fn start_polling(
        app_handle: AppHandle,
        last_copied_by_us: Arc<Mutex<Option<CopyMarker>>>,
        running: Arc<AtomicBool>,
    ) {
        use std::thread;
        use std::time::Duration;

        let mut clipboard = match Clipboard::new() {
            Ok(cb) => cb,
            Err(e) => {
                log::error!("Failed to create clipboard instance: {}", e);
                return;
            }
        };

        let mut last_text = String::new();
        let mut last_image: Option<Vec<u8>> = None;
        let mut last_ignored_concealed = false;

        while running.load(Ordering::SeqCst) {
            if Self::should_ignore_current_clipboard(&app_handle) {
                if !last_ignored_concealed {
                    log::info!(
                        "Skipping clipboard content marked as concealed/transient/autogenerated"
                    );
                }
                last_ignored_concealed = true;
                thread::sleep(Duration::from_millis(500));
                continue;
            }

            last_ignored_concealed = false;

            // Check for text changes
            if let Ok(text) = clipboard.get_text() {
                if text != last_text && !text.is_empty() {
                    Self::process_text_change(&app_handle, &last_copied_by_us, &text);
                    last_text = text;
                }
            }

            // Check for image changes
            if let Ok(image) = clipboard.get_image() {
                let payload = Self::normalize_image_payload(&image);
                if last_image.as_ref() != Some(&payload) {
                    Self::process_image_change(&app_handle, &last_copied_by_us, &image, &payload);
                    last_image = Some(payload);
                }
            }

            thread::sleep(Duration::from_millis(500));
        }
    }

    fn process_text_change(
        app_handle: &AppHandle,
        last_copied_by_us: &Arc<Mutex<Option<CopyMarker>>>,
        text: &str,
    ) {
        if Self::is_self_copied(last_copied_by_us, ContentType::Text, text.as_bytes()) {
            log::info!("⏭️ Skipping self-copied text ({} chars)", text.len());
            return;
        }

        log::info!("📋 Text clipboard changed: {} chars", text.len());
        let item = ClipItem {
            id: Uuid::new_v4().to_string(),
            content: text.as_bytes().to_vec(),
            thumbnail: None,
            content_type: ContentType::Text,
            timestamp: Utc::now().timestamp(),
            is_pinned: false,
            pin_order: None,
            label: None,
            group_name: None,
        };
        Self::save_to_storage(app_handle, item);
    }

    fn process_image_change(
        app_handle: &AppHandle,
        last_copied_by_us: &Arc<Mutex<Option<CopyMarker>>>,
        image: &ImageData,
        payload: &[u8],
    ) {
        if Self::is_self_copied(last_copied_by_us, ContentType::Image, payload) {
            log::info!(
                "⏭️ Skipping self-copied image ({}x{})",
                image.width,
                image.height
            );
            return;
        }

        let image_bytes = Self::image_to_bytes(image);
        log::info!("Image clipboard changed: {} bytes", image_bytes.len());

        let app_handle = app_handle.clone();
        tauri::async_runtime::spawn(async move {
            let content = Self::process_full_image(&image_bytes);
            let thumbnail = Some(Self::create_thumbnail(&content));
            let item = ClipItem {
                id: Uuid::new_v4().to_string(),
                content,
                thumbnail,
                content_type: ContentType::Image,
                timestamp: Utc::now().timestamp(),
                is_pinned: false,
                pin_order: None,
                label: None,
                group_name: None,
            };
            Self::save_to_storage(&app_handle, item);
        });
    }

    fn should_ignore_current_clipboard(app_handle: &AppHandle) -> bool {
        use crate::AppState;

        let state = app_handle.state::<AppState>();
        if !state.settings.get().ignore_concealed {
            return false;
        }

        clipboard_has_sensitive_marker()
    }

    fn is_self_copied(
        last_copied_by_us: &Arc<Mutex<Option<CopyMarker>>>,
        content_type: ContentType,
        payload: &[u8],
    ) -> bool {
        let Ok(last_copied) = last_copied_by_us.lock() else {
            log::warn!("Failed to lock self-copy marker");
            return false;
        };

        let Some(marker) = last_copied.as_ref() else {
            return false;
        };

        marker == &CopyMarker::from_payload(content_type, payload)
    }

    fn normalize_image_payload(image: &ImageData) -> Vec<u8> {
        let mut payload = Vec::with_capacity(16 + image.bytes.len());
        payload.extend_from_slice(&(image.width as u64).to_le_bytes());
        payload.extend_from_slice(&(image.height as u64).to_le_bytes());
        payload.extend_from_slice(image.bytes.as_ref());
        payload
    }

    fn save_to_storage(app_handle: &AppHandle, item: ClipItem) {
        use crate::storage::FrontendClipItem;
        use crate::tray::update_tray_menu;
        use crate::AppState;

        let mut item_for_emit = FrontendClipItem::from(item.clone());

        let state = app_handle.state::<AppState>();
        let max_history_items = state.settings.get().max_history_items;

        let result = {
            let storage = state.storage.lock().unwrap_or_else(|poisoned| {
                log::warn!("⚠️ Recovered from poisoned lock in clipboard monitor");
                poisoned.into_inner()
            });
            storage.insert(&item, max_history_items)
        };

        match result {
            Ok(existing_id) => {
                if let Some(id) = existing_id {
                    // It was a duplicate, update the emitted item to use the existing ID
                    // and current timestamp so frontend moves it to top
                    item_for_emit.id = id;
                    item_for_emit.timestamp = item.timestamp;
                    log::debug!("Updated existing item {} timestamp", item_for_emit.id);
                }

                app_handle.emit("clipboard-changed", &item_for_emit).ok();
                log::debug!("Updating tray menu...");
                update_tray_menu(app_handle);
                log::debug!("Clipboard item saved/updated and tray updated");
            }
            Err(e) => {
                log::error!("Failed to save clipboard item: {}", e);
            }
        }
    }

    fn image_to_bytes(image: &ImageData) -> Vec<u8> {
        use image::{ImageBuffer, RgbaImage};

        let img: RgbaImage = match ImageBuffer::from_raw(
            image.width as u32,
            image.height as u32,
            image.bytes.to_vec(),
        ) {
            Some(img) => img,
            None => {
                log::error!("Failed to create image buffer");
                return image.bytes.to_vec();
            }
        };

        let mut png_bytes = Vec::new();
        if let Err(e) = img.write_to(
            &mut std::io::Cursor::new(&mut png_bytes),
            image::ImageFormat::Png,
        ) {
            log::error!("Failed to encode PNG: {}", e);
            return image.bytes.to_vec();
        }

        png_bytes
    }

    fn create_thumbnail(image_bytes: &[u8]) -> Vec<u8> {
        const THUMBNAIL_SIZE: u32 = 256;

        match image::load_from_memory(image_bytes) {
            Ok(img) => {
                let thumbnail = img.resize(
                    THUMBNAIL_SIZE,
                    THUMBNAIL_SIZE,
                    image::imageops::FilterType::Lanczos3,
                );

                let mut buffer = Vec::new();
                if thumbnail
                    .write_to(
                        &mut std::io::Cursor::new(&mut buffer),
                        image::ImageFormat::Png,
                    )
                    .is_ok()
                {
                    log::info!(
                        "Created thumbnail: {}x{} -> {}x{}, {} bytes",
                        img.width(),
                        img.height(),
                        thumbnail.width(),
                        thumbnail.height(),
                        buffer.len()
                    );
                    buffer
                } else {
                    log::error!("Failed to encode thumbnail. Returning original bytes.");
                    image_bytes.to_vec()
                }
            }
            Err(e) => {
                log::warn!(
                    "Failed to decode image for thumbnail: {}. Returning original bytes.",
                    e
                );
                image_bytes.to_vec()
            }
        }
    }

    fn process_full_image(image_bytes: &[u8]) -> Vec<u8> {
        const MAX_SIZE: u32 = 2048;

        match image::load_from_memory(image_bytes) {
            Ok(img) => {
                let (w, h) = img.dimensions();

                let final_img = if w > MAX_SIZE || h > MAX_SIZE {
                    img.resize(MAX_SIZE, MAX_SIZE, image::imageops::FilterType::Lanczos3)
                } else {
                    img
                };

                let mut buffer = Vec::new();
                if final_img
                    .write_to(
                        &mut std::io::Cursor::new(&mut buffer),
                        image::ImageFormat::Png,
                    )
                    .is_ok()
                {
                    log::info!(
                        "Stored high-quality image: {}x{} -> {} bytes",
                        final_img.width(),
                        final_img.height(),
                        buffer.len()
                    );
                    buffer
                } else {
                    log::error!("Failed to encode high-quality image. Falling back to thumbnail.");
                    Self::create_thumbnail(image_bytes)
                }
            }
            Err(e) => {
                log::warn!(
                    "Failed to decode image for high-quality storage: {}. Falling back to thumbnail.",
                    e
                );
                Self::create_thumbnail(image_bytes)
            }
        }
    }
}

#[cfg(target_os = "macos")]
fn clipboard_has_sensitive_marker() -> bool {
    use objc2_app_kit::NSPasteboard;

    const IGNORED_PASTEBOARD_TYPES: &[&str] = &[
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ];

    let pasteboard = NSPasteboard::generalPasteboard();
    let Some(types) = pasteboard.types() else {
        return false;
    };

    for pasteboard_type in types.iter() {
        let type_name = pasteboard_type.to_string();

        if IGNORED_PASTEBOARD_TYPES.contains(&type_name.as_str()) {
            log::info!("Skipping macOS pasteboard marker type: {}", type_name);
            return true;
        }
    }

    false
}

#[cfg(target_os = "windows")]
fn clipboard_has_sensitive_marker() -> bool {
    use windows::Win32::Foundation::HWND;
    use windows::Win32::System::DataExchange::{CloseClipboard, OpenClipboard};

    unsafe {
        if let Err(e) = OpenClipboard(HWND(std::ptr::null_mut())) {
            log::warn!("Failed to open clipboard for privacy marker check: {}", e);
            return false;
        }

        let should_ignore = windows_clipboard_has_exclude_marker()
            || windows_can_include_clipboard_history_is_false();

        if let Err(e) = CloseClipboard() {
            log::warn!(
                "Failed to close clipboard after privacy marker check: {}",
                e
            );
        }

        should_ignore
    }
}

#[cfg(target_os = "windows")]
fn windows_clipboard_has_exclude_marker() -> bool {
    let format = windows_clipboard_format("ExcludeClipboardContentFromMonitorProcessing");
    if windows_clipboard_format_available(format) {
        log::info!("Skipping Windows clipboard history monitor opt-out marker");
        return true;
    }

    false
}

#[cfg(target_os = "windows")]
fn windows_can_include_clipboard_history_is_false() -> bool {
    let format = windows_clipboard_format("CanIncludeInClipboardHistory");
    if format == 0 || !windows_clipboard_format_available(format) {
        return false;
    }

    if windows_clipboard_dword(format) == Some(0) {
        log::info!("Skipping Windows clipboard history include marker set to 0");
        return true;
    }

    false
}

#[cfg(target_os = "windows")]
fn windows_clipboard_format(name: &str) -> u32 {
    use windows::core::PCWSTR;
    use windows::Win32::System::DataExchange::RegisterClipboardFormatW;

    let wide_name: Vec<u16> = name.encode_utf16().chain(std::iter::once(0)).collect();
    unsafe { RegisterClipboardFormatW(PCWSTR(wide_name.as_ptr())) }
}

#[cfg(target_os = "windows")]
fn windows_clipboard_format_available(format: u32) -> bool {
    use windows::Win32::System::DataExchange::IsClipboardFormatAvailable;

    format != 0 && unsafe { IsClipboardFormatAvailable(format).is_ok() }
}

#[cfg(target_os = "windows")]
fn windows_clipboard_dword(format: u32) -> Option<u32> {
    use windows::Win32::System::DataExchange::GetClipboardData;

    unsafe {
        let handle = GetClipboardData(format).ok()?;
        if handle.is_invalid() || GlobalSize(handle) < std::mem::size_of::<u32>() {
            return None;
        }

        let data = GlobalLock(handle);
        if data.is_null() {
            return None;
        }

        let bytes = std::slice::from_raw_parts(data.cast::<u8>(), std::mem::size_of::<u32>());
        let value = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
        let _ = GlobalUnlock(handle);
        Some(value)
    }
}

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
fn clipboard_has_sensitive_marker() -> bool {
    false
}
