use arboard::{Clipboard, ImageData};
use chrono::Utc;
use clipboard_master::{CallbackResult, ClipboardHandler, Master, Shutdown};
use image::{DynamicImage, ImageBuffer, RgbaImage};
use std::sync::{
    atomic::{AtomicBool, Ordering},
    mpsc, Arc, Mutex,
};
use std::thread::JoinHandle;
use std::time::Duration;
use tauri::{AppHandle, Emitter, Manager};
use uuid::Uuid;

use crate::storage::{ClipItem, ContentType, CopyMarker};

type MonitorReadySender = mpsc::Sender<Result<(), String>>;
const MONITOR_STOP_TIMEOUT: Duration = Duration::from_secs(2);

#[cfg(target_os = "windows")]
#[link(name = "kernel32")]
extern "system" {
    fn GlobalLock(hmem: windows::Win32::Foundation::HANDLE) -> *mut std::ffi::c_void;
    fn GlobalSize(hmem: windows::Win32::Foundation::HANDLE) -> usize;
    fn GlobalUnlock(hmem: windows::Win32::Foundation::HANDLE) -> i32;
}

pub struct ClipboardMonitor {
    app_handle: AppHandle,
    last_copied_by_us: Arc<Mutex<Option<CopyMarker>>>,
    running: Arc<AtomicBool>,
    shutdown: Arc<Mutex<Option<Shutdown>>>,
    handle: Option<JoinHandle<()>>,
}

struct Handler {
    app_handle: AppHandle,
    last_copied_by_us: Arc<Mutex<Option<CopyMarker>>>,
    running: Arc<AtomicBool>,
    last_text: String,
    last_image_marker: Option<CopyMarker>,
}

struct ProcessedClipboardImage {
    content_png: Vec<u8>,
    thumbnail_png: Vec<u8>,
    marker: CopyMarker,
}

impl ClipboardHandler for Handler {
    fn on_clipboard_change(&mut self) -> CallbackResult {
        if !self.running.load(Ordering::SeqCst) {
            return CallbackResult::Stop;
        }

        let mut clipboard = match Clipboard::new() {
            Ok(cb) => cb,
            Err(e) => {
                log::error!("Failed to create clipboard instance in handler: {}", e);
                return CallbackResult::Next;
            }
        };

        if ClipboardMonitor::should_ignore_current_clipboard(&self.app_handle) {
            log::info!("Skipping clipboard change marked as concealed/transient/autogenerated");
            return CallbackResult::Next;
        }

        // Check for text changes
        if let Ok(text) = clipboard.get_text() {
            if text != self.last_text && !text.is_empty() {
                ClipboardMonitor::process_text_change(
                    &self.app_handle,
                    &self.last_copied_by_us,
                    &text,
                );
                self.last_text = text;
            }
        }

        // Check for image changes
        if let Ok(image) = clipboard.get_image() {
            let marker = ClipboardMonitor::image_marker(&image);
            if self.last_image_marker.as_ref() != Some(&marker) {
                ClipboardMonitor::process_image_change(
                    &self.app_handle,
                    &self.last_copied_by_us,
                    &self.running,
                    &image,
                    &marker,
                );
                self.last_image_marker = Some(marker);
            }
        }

        CallbackResult::Next
    }

    fn on_clipboard_error(&mut self, error: std::io::Error) -> CallbackResult {
        log::error!("Clipboard error: {}", error);
        CallbackResult::Next
    }
}

impl ClipboardMonitor {
    pub fn new(app_handle: AppHandle, last_copied_by_us: Arc<Mutex<Option<CopyMarker>>>) -> Self {
        Self {
            app_handle,
            last_copied_by_us,
            running: Arc::new(AtomicBool::new(false)),
            shutdown: Arc::new(Mutex::new(None)),
            handle: None,
        }
    }

    pub fn start(&mut self) -> Result<(), String> {
        self.running.store(true, Ordering::SeqCst);
        let app_handle = self.app_handle.clone();
        let last_copied_by_us = self.last_copied_by_us.clone();
        let running = self.running.clone();
        let shutdown_slot = self.shutdown.clone();
        let (ready_sender, ready_receiver) = mpsc::channel();

        // Start event-driven monitoring thread
        let handle = std::thread::spawn(move || {
            log::info!("Clipboard monitoring thread started (event-driven)");

            let handler = Handler {
                app_handle: app_handle.clone(),
                last_copied_by_us: last_copied_by_us.clone(),
                running: running.clone(),
                last_text: String::new(),
                last_image_marker: None,
            };

            // Start the clipboard master - this blocks until the application exits
            match Master::new(handler) {
                Ok(mut master) => {
                    // Hand the shutdown channel to the monitor before start()
                    // returns, so stop() can always signal run() before join().
                    *crate::safe_lock(&shutdown_slot) = Some(master.shutdown_channel());
                    let run_returned = Arc::new(AtomicBool::new(false));
                    let run_returned_for_ready = run_returned.clone();
                    let ready_sender_for_event = ready_sender.clone();
                    std::thread::spawn(move || {
                        std::thread::sleep(Duration::from_millis(250));
                        if !run_returned_for_ready.load(Ordering::SeqCst) {
                            let _ = ready_sender_for_event.send(Ok(()));
                        }
                    });

                    let run_result = master.run();
                    run_returned.store(true, Ordering::SeqCst);
                    if let Err(e) = run_result {
                        log::error!("Clipboard master failed: {}", e);
                        log::warn!("Falling back to polling mode...");
                        Self::start_polling(
                            app_handle,
                            last_copied_by_us,
                            running,
                            Some(ready_sender),
                        );
                    }
                }
                Err(e) => {
                    log::error!("Failed to create clipboard master: {}", e);
                    log::warn!("Falling back to polling mode...");
                    Self::start_polling(app_handle, last_copied_by_us, running, Some(ready_sender));
                }
            }
        });

        self.handle = Some(handle);
        match ready_receiver.recv() {
            Ok(Ok(())) => Ok(()),
            Ok(Err(e)) => {
                self.running.store(false, Ordering::SeqCst);
                if let Some(handle) = self.handle.take() {
                    let _ = handle.join();
                }
                Err(e)
            }
            Err(e) => {
                self.running.store(false, Ordering::SeqCst);
                if let Some(handle) = self.handle.take() {
                    let _ = handle.join();
                }
                Err(format!("Clipboard monitor failed to start: {}", e))
            }
        }
    }

    /// Stop the monitor and wait for its thread to exit.
    pub fn stop(mut self) {
        self.running.store(false, Ordering::SeqCst);
        if let Some(shutdown) = crate::safe_lock(&self.shutdown).take() {
            shutdown.signal();
        }
        if let Some(handle) = self.handle.take() {
            join_monitor_thread_with_timeout(handle);
        }
    }

    // Fallback polling implementation
    fn start_polling(
        app_handle: AppHandle,
        last_copied_by_us: Arc<Mutex<Option<CopyMarker>>>,
        running: Arc<AtomicBool>,
        ready_sender: Option<MonitorReadySender>,
    ) {
        use std::thread;

        let mut clipboard = match Clipboard::new() {
            Ok(cb) => cb,
            Err(e) => {
                let message = format!("Failed to create clipboard instance: {}", e);
                log::error!("{}", message);
                running.store(false, Ordering::SeqCst);
                if let Some(ready_sender) = ready_sender {
                    let _ = ready_sender.send(Err(message));
                }
                return;
            }
        };
        if let Some(ready_sender) = ready_sender {
            let _ = ready_sender.send(Ok(()));
        }

        let mut last_text = String::new();
        let mut last_image_marker: Option<CopyMarker> = None;
        let mut last_ignored_concealed = false;

        while running.load(Ordering::SeqCst) {
            if Self::should_ignore_current_clipboard(&app_handle) {
                if !last_ignored_concealed {
                    log::info!(
                        "Skipping clipboard content marked as concealed/transient/autogenerated"
                    );
                }
                last_ignored_concealed = true;
                thread::sleep(Duration::from_millis(500));
                continue;
            }

            last_ignored_concealed = false;

            // Check for text changes
            if let Ok(text) = clipboard.get_text() {
                if text != last_text && !text.is_empty() {
                    Self::process_text_change(&app_handle, &last_copied_by_us, &text);
                    last_text = text;
                }
            }

            // Check for image changes
            if let Ok(image) = clipboard.get_image() {
                let marker = Self::image_marker(&image);
                if last_image_marker.as_ref() != Some(&marker) {
                    Self::process_image_change(
                        &app_handle,
                        &last_copied_by_us,
                        &running,
                        &image,
                        &marker,
                    );
                    last_image_marker = Some(marker);
                }
            }

            thread::sleep(Duration::from_millis(500));
        }
    }

    fn process_text_change(
        app_handle: &AppHandle,
        last_copied_by_us: &Arc<Mutex<Option<CopyMarker>>>,
        text: &str,
    ) {
        let marker = CopyMarker::from_payload(ContentType::Text, text.as_bytes());
        if Self::is_self_copied(last_copied_by_us, &marker) {
            log::info!("⏭️ Skipping self-copied text ({} chars)", text.len());
            return;
        }

        log::info!("📋 Text clipboard changed: {} chars", text.len());
        let item = ClipItem {
            id: Uuid::new_v4().to_string(),
            content: text.as_bytes().to_vec(),
            thumbnail: None,
            content_type: ContentType::Text,
            timestamp: Utc::now().timestamp(),
            is_pinned: false,
            pin_order: None,
            label: None,
            group_name: None,
        };
        Self::save_to_storage(app_handle, item);
    }

    fn process_image_change(
        app_handle: &AppHandle,
        last_copied_by_us: &Arc<Mutex<Option<CopyMarker>>>,
        running: &Arc<AtomicBool>,
        image: &ImageData,
        marker: &CopyMarker,
    ) {
        if Self::is_self_copied(last_copied_by_us, marker) {
            log::info!(
                "⏭️ Skipping self-copied image ({}x{})",
                image.width,
                image.height
            );
            return;
        }

        let width = image.width;
        let height = image.height;
        let rgba_bytes = image.bytes.to_vec();
        let marker = marker.clone();
        log::info!(
            "Image clipboard changed: {}x{}, {} RGBA bytes",
            width,
            height,
            rgba_bytes.len()
        );

        let app_handle = app_handle.clone();
        let running = running.clone();
        tauri::async_runtime::spawn(async move {
            let processed = tauri::async_runtime::spawn_blocking(move || {
                Self::process_clipboard_image(width, height, rgba_bytes, marker)
            })
            .await;

            match processed {
                Ok(Ok(processed)) => {
                    if !running.load(Ordering::SeqCst) {
                        log::debug!("Skipping processed image save after monitor stopped");
                        return;
                    }

                    let item = ClipItem {
                        id: Uuid::new_v4().to_string(),
                        content: processed.content_png,
                        thumbnail: Some(processed.thumbnail_png),
                        content_type: processed.marker.content_type,
                        timestamp: Utc::now().timestamp(),
                        is_pinned: false,
                        pin_order: None,
                        label: None,
                        group_name: None,
                    };
                    Self::save_to_storage(&app_handle, item);
                }
                Ok(Err(e)) => log::error!("Failed to process clipboard image: {}", e),
                Err(e) => log::error!("Image processing task failed: {}", e),
            }
        });
    }

    fn should_ignore_current_clipboard(app_handle: &AppHandle) -> bool {
        use crate::AppState;

        let state = app_handle.state::<AppState>();
        if !state.settings.get().ignore_concealed {
            return false;
        }

        clipboard_has_sensitive_marker()
    }

    fn is_self_copied(
        last_copied_by_us: &Arc<Mutex<Option<CopyMarker>>>,
        expected_marker: &CopyMarker,
    ) -> bool {
        let Ok(last_copied) = last_copied_by_us.lock() else {
            log::warn!("Failed to lock self-copy marker");
            return false;
        };

        let Some(marker) = last_copied.as_ref() else {
            return false;
        };

        marker == expected_marker
    }

    fn image_marker(image: &ImageData) -> CopyMarker {
        CopyMarker::from_normalized_image_parts(image.width, image.height, image.bytes.as_ref())
    }

    fn save_to_storage(app_handle: &AppHandle, item: ClipItem) {
        use crate::storage::{ClipPreviewItem, FrontendClipItem};
        use crate::tray::update_tray_menu;
        use crate::AppState;

        let state = app_handle.state::<AppState>();
        let max_history_items = state.settings.get().max_history_items;

        let result = {
            let storage = state.storage.lock().unwrap_or_else(|poisoned| {
                log::warn!("⚠️ Recovered from poisoned lock in clipboard monitor");
                poisoned.into_inner()
            });

            storage
                .insert(&item, max_history_items)
                .and_then(|existing_id| {
                    if let Some(id) = existing_id {
                        log::debug!("Updated existing item {} timestamp", id);
                        if let Some(existing_item) = storage.get_preview_by_id(&id)? {
                            return Ok(FrontendClipItem::from_preview(existing_item));
                        }

                        log::warn!("Duplicate item {} was not found after timestamp update", id);
                        return Ok(FrontendClipItem::from_preview(
                            ClipPreviewItem::from_clip_item_with_id(&item, id),
                        ));
                    }

                    Ok(FrontendClipItem::from_preview(
                        ClipPreviewItem::from_clip_item(&item),
                    ))
                })
        };

        match result {
            Ok(item_for_emit) => {
                app_handle.emit("clipboard-changed", &item_for_emit).ok();
                log::debug!("Updating tray menu...");
                update_tray_menu(app_handle);
                log::debug!("Clipboard item saved/updated and tray updated");
            }
            Err(e) => {
                log::error!("Failed to save clipboard item: {}", e);
            }
        }
    }

    fn process_clipboard_image(
        width: usize,
        height: usize,
        rgba_bytes: Vec<u8>,
        marker: CopyMarker,
    ) -> Result<ProcessedClipboardImage, String> {
        const THUMBNAIL_SIZE: u32 = 256;

        let image: RgbaImage = ImageBuffer::from_raw(width as u32, height as u32, rgba_bytes)
            .ok_or_else(|| "Invalid clipboard image buffer dimensions".to_string())?;
        let image = DynamicImage::ImageRgba8(image);

        let thumbnail = image.resize(
            THUMBNAIL_SIZE,
            THUMBNAIL_SIZE,
            image::imageops::FilterType::Lanczos3,
        );
        let content_png = Self::encode_png(&image)?;
        let thumbnail_png = Self::encode_png(&thumbnail)?;

        log::info!(
            "Processed clipboard image: {}x{} -> {} bytes, thumbnail {} bytes",
            image.width(),
            image.height(),
            content_png.len(),
            thumbnail_png.len()
        );

        Ok(ProcessedClipboardImage {
            content_png,
            thumbnail_png,
            marker,
        })
    }

    fn encode_png(image: &DynamicImage) -> Result<Vec<u8>, String> {
        let mut buffer = Vec::new();
        image
            .write_to(
                &mut std::io::Cursor::new(&mut buffer),
                image::ImageFormat::Png,
            )
            .map_err(|e| format!("Failed to encode PNG: {}", e))?;
        Ok(buffer)
    }
}

fn join_monitor_thread_with_timeout(handle: JoinHandle<()>) {
    let (sender, receiver) = mpsc::channel();
    std::thread::spawn(move || {
        let result = handle.join();
        let _ = sender.send(result);
    });

    match receiver.recv_timeout(MONITOR_STOP_TIMEOUT) {
        Ok(Ok(())) => {}
        Ok(Err(_)) => log::warn!("Clipboard monitoring thread panicked while stopping"),
        Err(mpsc::RecvTimeoutError::Timeout) => log::warn!(
            "Timed out waiting for clipboard monitoring thread to stop; continuing shutdown"
        ),
        Err(mpsc::RecvTimeoutError::Disconnected) => {
            log::warn!("Clipboard monitoring thread join waiter disconnected")
        }
    }
}

#[cfg(target_os = "macos")]
fn clipboard_has_sensitive_marker() -> bool {
    use objc2_app_kit::NSPasteboard;

    const IGNORED_PASTEBOARD_TYPES: &[&str] = &[
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ];

    let pasteboard = NSPasteboard::generalPasteboard();
    let Some(types) = pasteboard.types() else {
        return false;
    };

    for pasteboard_type in types.iter() {
        let type_name = pasteboard_type.to_string();

        if IGNORED_PASTEBOARD_TYPES.contains(&type_name.as_str()) {
            log::info!("Skipping macOS pasteboard marker type: {}", type_name);
            return true;
        }
    }

    false
}

#[cfg(target_os = "windows")]
fn clipboard_has_sensitive_marker() -> bool {
    use windows::Win32::Foundation::HWND;
    use windows::Win32::System::DataExchange::{CloseClipboard, OpenClipboard};

    unsafe {
        if let Err(e) = OpenClipboard(HWND(std::ptr::null_mut())) {
            log::warn!("Failed to open clipboard for privacy marker check: {}", e);
            return false;
        }

        let should_ignore = windows_clipboard_has_exclude_marker()
            || windows_can_include_clipboard_history_is_false();

        if let Err(e) = CloseClipboard() {
            log::warn!(
                "Failed to close clipboard after privacy marker check: {}",
                e
            );
        }

        should_ignore
    }
}

#[cfg(target_os = "windows")]
fn windows_clipboard_has_exclude_marker() -> bool {
    let format = windows_clipboard_format("ExcludeClipboardContentFromMonitorProcessing");
    if windows_clipboard_format_available(format) {
        log::info!("Skipping Windows clipboard history monitor opt-out marker");
        return true;
    }

    false
}

#[cfg(target_os = "windows")]
fn windows_can_include_clipboard_history_is_false() -> bool {
    let format = windows_clipboard_format("CanIncludeInClipboardHistory");
    if format == 0 || !windows_clipboard_format_available(format) {
        return false;
    }

    if windows_clipboard_dword(format) == Some(0) {
        log::info!("Skipping Windows clipboard history include marker set to 0");
        return true;
    }

    false
}

#[cfg(target_os = "windows")]
fn windows_clipboard_format(name: &str) -> u32 {
    use windows::core::PCWSTR;
    use windows::Win32::System::DataExchange::RegisterClipboardFormatW;

    let wide_name: Vec<u16> = name.encode_utf16().chain(std::iter::once(0)).collect();
    unsafe { RegisterClipboardFormatW(PCWSTR(wide_name.as_ptr())) }
}

#[cfg(target_os = "windows")]
fn windows_clipboard_format_available(format: u32) -> bool {
    use windows::Win32::System::DataExchange::IsClipboardFormatAvailable;

    format != 0 && unsafe { IsClipboardFormatAvailable(format).is_ok() }
}

#[cfg(target_os = "windows")]
fn windows_clipboard_dword(format: u32) -> Option<u32> {
    use windows::Win32::System::DataExchange::GetClipboardData;

    unsafe {
        let handle = GetClipboardData(format).ok()?;
        if handle.is_invalid() || GlobalSize(handle) < std::mem::size_of::<u32>() {
            return None;
        }

        let data = GlobalLock(handle);
        if data.is_null() {
            return None;
        }

        let bytes = std::slice::from_raw_parts(data.cast::<u8>(), std::mem::size_of::<u32>());
        let value = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
        let _ = GlobalUnlock(handle);
        Some(value)
    }
}

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
fn clipboard_has_sensitive_marker() -> bool {
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn processed_clipboard_image_uses_raw_rgba_marker() {
        let rgba_bytes = vec![255, 0, 0, 255];
        let marker = CopyMarker::from_normalized_image_parts(1, 1, &rgba_bytes);

        let processed =
            ClipboardMonitor::process_clipboard_image(1, 1, rgba_bytes, marker.clone()).unwrap();

        assert_eq!(marker, processed.marker);
        assert!(!processed.content_png.is_empty());
        assert!(!processed.thumbnail_png.is_empty());
    }

    #[test]
    fn processed_clipboard_image_preserves_original_content_dimensions() {
        let width = 2050;
        let height = 1;
        let rgba_bytes = vec![255; width * height * 4];
        let marker = CopyMarker::from_normalized_image_parts(width, height, &rgba_bytes);

        let processed =
            ClipboardMonitor::process_clipboard_image(width, height, rgba_bytes, marker).unwrap();
        let content = image::load_from_memory(&processed.content_png).unwrap();

        assert_eq!(width as u32, content.width());
        assert_eq!(height as u32, content.height());
    }
}
